---
title: "project proposal"
date: "2024-11-08"
output: github_document
---

# Buzzing Threats: Climate Change, Mosquitoes, and West Nile Virus in NYC
Mahdi Maktabi (mm6410), Johnstone Tcheou (jt3466), Samina Rashiq (ssr2195), Sean Sorek (ss7332)

## Motivation 

As temperatures increase over the years, the intersection of OneHealth and vector-borne infectious diseases becomes increasingly relevant. Rising temperatures in temperate areas like NYC makes these climates more hospitable for many cold-blooded mosquito species. As a result, mosquito-borne illnesses like Dengue, Zika, West Nile, and more are becoming more prevalent in NYC. In this project, we intend to visualize the rise of West Nile Virus and the effectiveness of control methods.

## Final products

Figures:

* Distribution of change in temperatures in NYC (can separate this by borough)
* Trends of incidence of mosquito-borne illnesses in NYC
* Map heat vulnerability (or average temperature readings throughout city and see how this compares to mosquito sightings)

## Anticipated data sources

[NYC Environment and Health Data Portal - Heat vulnerability index by neighborhood tabulation area (NTA)](https://a816-dohbesp.nyc.gov/IndicatorPublic/data-explorer/climate/?id=2411#display=summary)

[NYC DOHMH - positive mosquitoes dashboard and table](https://www.nyc.gov/site/doh/health/health-topics/west-nile-virus-activity.page)

[NYC DOHMH - mosquito surveillance plan 2024](https://www.nyc.gov/assets/doh/downloads/pdf/wnv/2024/wnvplan2024.pdf)

## Planned analyses/visualizations/challenges

* Visualizations 
  * Prevalence of difference mosquito diseases from 2015-2020
  * Graph of changing West Nile Virus prevalence (and maybe case fatality rate)
  * Map of neighborhood heat vulnerability and West Nile Virus detection 
* Challenges
  * Ensuring that all data sets have similar indicators/variables so they can be merged (and are complete)
  * Comparability of ZIP code metrics to NTA metrics (like WNV prevalence by ZIP to heat vulnerability by NTA)

## Planned timeline 

* November 8: Finding and confirming appropriate datasets to use
* November 11-15: Project review meeting and finalize analysis plan
* November 30: Cleaning and merging datasets
* December 7: Creating visualizations, site, and screencast 