<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>regression_models</title>

<script src="site_libs/header-attrs-2.28/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="data_exploration.html">Data Exploration</a>
</li>
<li>
  <a href="data_analysis.html">Data Analysis</a>
</li>
<li>
  <a href="https://jt3466.shinyapps.io/nyc_wnv/">Dashboard</a>
</li>
<li>
  <a href="mailto:&lt;mm6410@cumc.columbia.edu&gt;,&lt;jt3466@cumc.columbia.edu&gt;, &lt;ssr2195@cumc.columbia.edu&gt;, &lt;ss7332@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/tcheouj/p8105_wnv_nyc">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">regression_models</h1>

</div>


<div id="data-import" class="section level1">
<h1>Data import</h1>
<p>First, we need to import our WNV data and predictor data. Ultimately,
we are only modeling WNV+ mosquitoes, so we are actually just using the
mosquito data and the weather data to predict WNV+ mosquito counts.
Since Heat Vulnerability Index (HVI) is a quantitative proxy for human
vulnerability to extreme heat and heatstroke, we do not hypothesize it
to be causally relevant. This is supported by the lack of association
between HVI and WNV+ mosquito count.</p>
<pre class="r"><code>wnv_cases &lt;- read_csv(&quot;cleaned_data/wnv_cases.csv&quot;)
wnv_mosquitoes &lt;- read_csv(&quot;cleaned_data/wnv_mosquitoes_test.csv&quot;) 
heat_vuln &lt;- read_csv(&quot;cleaned_data/heat_vuln.csv&quot;)
day_weather &lt;- read_csv(&quot;cleaned_data/day_weather.csv&quot;)</code></pre>
</div>
<div id="model-with-year" class="section level1">
<h1>Model with year</h1>
<p>This is the simplest model, predicting counts of WNV+ mosquitoes
using year. Using our mosquito count data, we want to get counts per
year to model from. As such, we <code>mutate</code> to create a year
variable based on the date variable, <code>group_by</code> year, and
calculate the count for each year.</p>
<pre class="r"><code>mosq_count_by_year &lt;- 
  wnv_mosquitoes |&gt;
  mutate(year = lubridate::year(date)) |&gt;
  group_by(year) |&gt;
  summarise(count = n()) |&gt;
  filter(year &lt; 3000)

mosq_count_by_year |&gt; 
  knitr::kable(col.names = c(&quot;Year&quot;, &quot;Count of WNV+ mosquitoes&quot;)) </code></pre>
<table>
<thead>
<tr class="header">
<th align="right">Year</th>
<th align="right">Count of WNV+ mosquitoes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2021</td>
<td align="right">732</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">789</td>
</tr>
<tr class="odd">
<td align="right">2023</td>
<td align="right">711</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">692</td>
</tr>
</tbody>
</table>
<pre class="r"><code>fit1 &lt;- glm(count ~ year, mosq_count_by_year, family = &quot;poisson&quot;)

fit1 |&gt; 
  tidy() |&gt; 
  knitr::kable(
    digits = 4,
    col.names = c(&quot;Term&quot;, &quot;Estimate&quot;, &quot;Standard error&quot;, &quot;Tes statistic&quot;, &quot;p value&quot;)
  )</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Term</th>
<th align="right">Estimate</th>
<th align="right">Standard error</th>
<th align="right">Tes statistic</th>
<th align="right">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">61.3872</td>
<td align="right">33.4636</td>
<td align="right">1.8344</td>
<td align="right">0.0666</td>
</tr>
<tr class="even">
<td align="left">year</td>
<td align="right">-0.0271</td>
<td align="right">0.0165</td>
<td align="right">-1.6374</td>
<td align="right">0.1016</td>
</tr>
</tbody>
</table>
<pre class="r"><code>fit1 |&gt; 
  glance() |&gt; 
  knitr::kable(
    digits = 4,
    col.names = c(&quot;Null deviance&quot;, &quot;Null df&quot;, &quot;Log likelihood&quot;, &quot;AIC&quot;, &quot;BIC&quot;, &quot;Deviance&quot;, &quot;Residual df&quot;, &quot;Number of observations&quot;)
  )</code></pre>
<table>
<colgroup>
<col width="14%" />
<col width="8%" />
<col width="15%" />
<col width="8%" />
<col width="8%" />
<col width="9%" />
<col width="12%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Null deviance</th>
<th align="right">Null df</th>
<th align="right">Log likelihood</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">Deviance</th>
<th align="right">Residual df</th>
<th align="right">Number of observations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">7.1572</td>
<td align="right">3</td>
<td align="right">-19.1003</td>
<td align="right">42.2006</td>
<td align="right">40.9732</td>
<td align="right">4.4754</td>
<td align="right">2</td>
<td align="right">4</td>
</tr>
</tbody>
</table>
<p>Since we are modeling counts of WNV+ mosquitoes, viable models for
count data would be a Poisson regression or negative binomial
regression. Our first initial model is a Poisson regression predicting
counts of mosquitoes using year alone.</p>
<p>As expected, year does not really predict count much, with an
estimated -0.0271 count of mosquitoes for each additional year. The
parameter is also not significant at the 0.05 level, with a p value of
0.1016.</p>
</div>
<div id="model-with-month" class="section level1">
<h1>Model with month</h1>
<p>As for the simple model using year, we want to get counts of
mosquitoes but per month this time instead of year. We create a month
variable using <code>mutate</code>, and <code>group_by</code> is used
again to calculate counts of mosquitoes per month.</p>
<pre class="r"><code>mosq_count_by_month &lt;- 
  wnv_mosquitoes |&gt;
  mutate(month = lubridate::month(date)) |&gt;
  group_by(month) |&gt;
  summarise(count = n())

mosq_count_by_month |&gt; 
  knitr::kable(col.names = c(&quot;Month&quot;, &quot;Count of WNV+ mosquitoes&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">Month</th>
<th align="right">Count of WNV+ mosquitoes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">6</td>
<td align="right">48</td>
</tr>
<tr class="even">
<td align="right">7</td>
<td align="right">692</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="right">1282</td>
</tr>
<tr class="even">
<td align="right">9</td>
<td align="right">782</td>
</tr>
<tr class="odd">
<td align="right">10</td>
<td align="right">120</td>
</tr>
</tbody>
</table>
<pre class="r"><code>mosq_count_by_month |&gt; 
  ggplot(aes(x = month, y = count)) +
  geom_bar(stat = &quot;identity&quot;, fill = &quot;#440154FF&quot;) +
  guides(
    fill = &quot;none&quot;
  )</code></pre>
<p><img src="regression_models_files/figure-html/month%20data-1.png" width="672" /></p>
<p>As shown on the table, the bulk of the counts are in the middle of
summer in August, with 1282 mosquitoes, tapering off towards the
beginning and end in June and October. The start of data collection in
June has the least number of WNV+ mosquitoes with 48. When plotted, the
distribution is also approximately normal.</p>
<pre class="r"><code>fit2 &lt;- glm(count ~ month, mosq_count_by_month, family = &quot;poisson&quot;) 

fit2 |&gt; 
  tidy() |&gt; 
  knitr::kable(
    digits = 4,
    col.names = c(&quot;Term&quot;, &quot;Estimate&quot;, &quot;Standard error&quot;, &quot;Test statistic&quot;, &quot;p value&quot;)
  )</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Term</th>
<th align="right">Estimate</th>
<th align="right">Standard error</th>
<th align="right">Test statistic</th>
<th align="right">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">6.0493</td>
<td align="right">0.1074</td>
<td align="right">56.3390</td>
<td align="right">0.0000</td>
</tr>
<tr class="even">
<td align="left">month</td>
<td align="right">0.0400</td>
<td align="right">0.0131</td>
<td align="right">3.0589</td>
<td align="right">0.0022</td>
</tr>
</tbody>
</table>
<pre class="r"><code>fit2 |&gt; 
  glance() |&gt; 
  knitr::kable(
    digits = 4,
    col.names = c(&quot;Null deviance&quot;, &quot;Null df&quot;, &quot;Log likelihood&quot;, &quot;AIC&quot;, &quot;BIC&quot;, &quot;Deviance&quot;, &quot;Residual df&quot;, &quot;Number of observations&quot;)
  )</code></pre>
<table>
<colgroup>
<col width="14%" />
<col width="8%" />
<col width="15%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="12%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Null deviance</th>
<th align="right">Null df</th>
<th align="right">Log likelihood</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">Deviance</th>
<th align="right">Residual df</th>
<th align="right">Number of observations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2079.812</td>
<td align="right">4</td>
<td align="right">-1054.328</td>
<td align="right">2112.656</td>
<td align="right">2111.875</td>
<td align="right">2070.445</td>
<td align="right">3</td>
<td align="right">5</td>
</tr>
</tbody>
</table>
<p>Our second model modeling mosquito count predicted by month only has
a significant regression parameter of 0.04 mosquitoes for every increase
by 1 month, with a p value of 0.0022.</p>
<pre class="r"><code>mosq_count_by_month |&gt; 
  cbind(pred = predict(fit2, type = &quot;response&quot;)) |&gt; 
  ggplot(aes(x = month, y = count)) +
  geom_point(color = &quot;#404688FF&quot;, alpha = 0.5) + 
  geom_line(aes(y = pred))</code></pre>
<p><img src="regression_models_files/figure-html/month%20model%20fit-1.png" width="672" /></p>
<p>However, despite a significant model, the model does not fit our
dataset well, so it is not useful in predicting counts. When plotting
the predicted values against the observed values, the predicted values
are linear since model is represented as a linear term, while our
observed counts are parabolic.</p>
<pre class="r"><code># mosq_cases |&gt; 
#   ggplot(aes(x = weekyear, y = count)) +
#   geom_point()

fit3 &lt;- glm(count ~ month + I(month^2), mosq_count_by_month, family = &quot;poisson&quot;)

fit3 |&gt; 
  tidy() |&gt; 
  knitr::kable(
    digits = 4,
    col.names = c(&quot;Term&quot;, &quot;Estimate&quot;, &quot;Standard error&quot;, &quot;Test statistic&quot;, &quot;p value&quot;)
  )</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Term</th>
<th align="right">Estimate</th>
<th align="right">Standard error</th>
<th align="right">Test statistic</th>
<th align="right">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-36.5164</td>
<td align="right">1.2301</td>
<td align="right">-29.6863</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">month</td>
<td align="right">10.8205</td>
<td align="right">0.3058</td>
<td align="right">35.3854</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">I(month^2)</td>
<td align="right">-0.6694</td>
<td align="right">0.0189</td>
<td align="right">-35.4324</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<pre class="r"><code>fit3 |&gt; 
  glance() |&gt; 
  knitr::kable(
    digits = 4,
    col.names = c(&quot;Null deviance&quot;, &quot;Null df&quot;, &quot;Log likelihood&quot;, &quot;AIC&quot;, &quot;BIC&quot;, &quot;Deviance&quot;, &quot;Residual df&quot;, &quot;Number of observations&quot;)
  )</code></pre>
<table>
<colgroup>
<col width="14%" />
<col width="8%" />
<col width="15%" />
<col width="8%" />
<col width="7%" />
<col width="9%" />
<col width="12%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Null deviance</th>
<th align="right">Null df</th>
<th align="right">Log likelihood</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">Deviance</th>
<th align="right">Residual df</th>
<th align="right">Number of observations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2079.812</td>
<td align="right">4</td>
<td align="right">-30.4953</td>
<td align="right">66.9907</td>
<td align="right">65.819</td>
<td align="right">22.7796</td>
<td align="right">2</td>
<td align="right">5</td>
</tr>
</tbody>
</table>
<p>With this model, both linear and second order terms are significant
predictors of mosquito counts, with p values of 0 and 0,
respectively.</p>
<pre class="r"><code>mosq_count_by_month |&gt; 
  cbind(pred = predict(fit3, type = &quot;response&quot;)) |&gt; 
  ggplot(aes(x = month, y = count)) +
  geom_point(color = &quot;#3B528BFF&quot;, alpha = 0.5, size = 2) + 
  geom_line(aes(y = pred))</code></pre>
<p><img src="regression_models_files/figure-html/linear%20and%20quadratic%20month%20fit-1.png" width="672" /></p>
<p>With an included second order term for month, our predicted values
better fit the observed values, depicting the parabolic shape of the
data.</p>
</div>
<div id="model-with-month-and-year" class="section level1">
<h1>Model with month and year</h1>
<p>Now that we are predicting both month and year, we want to get counts
per each combination of month and year. We <code>mutate</code> to create
month and year variables again, <code>group_by</code> month and year
both this time, and get the mosquito counts per each combination as
follows.</p>
<pre class="r"><code>mosq_month_year &lt;- 
  wnv_mosquitoes |&gt;
  mutate(month = lubridate::month(date),
         year = lubridate::year(date)) |&gt;
  group_by(year, month) |&gt;
  summarise(count = n()) |&gt;
  filter(year &lt; 3000)

mosq_month_year |&gt; 
  knitr::kable(col.names = c(&quot;Year&quot;, &quot;Month&quot;, &quot;Count of WNV+ mosquitoes&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">Year</th>
<th align="right">Month</th>
<th align="right">Count of WNV+ mosquitoes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2021</td>
<td align="right">6</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="right">2021</td>
<td align="right">7</td>
<td align="right">162</td>
</tr>
<tr class="odd">
<td align="right">2021</td>
<td align="right">8</td>
<td align="right">303</td>
</tr>
<tr class="even">
<td align="right">2021</td>
<td align="right">9</td>
<td align="right">200</td>
</tr>
<tr class="odd">
<td align="right">2021</td>
<td align="right">10</td>
<td align="right">63</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">6</td>
<td align="right">8</td>
</tr>
<tr class="odd">
<td align="right">2022</td>
<td align="right">7</td>
<td align="right">109</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">8</td>
<td align="right">358</td>
</tr>
<tr class="odd">
<td align="right">2022</td>
<td align="right">9</td>
<td align="right">293</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">10</td>
<td align="right">21</td>
</tr>
<tr class="odd">
<td align="right">2023</td>
<td align="right">7</td>
<td align="right">72</td>
</tr>
<tr class="even">
<td align="right">2023</td>
<td align="right">8</td>
<td align="right">342</td>
</tr>
<tr class="odd">
<td align="right">2023</td>
<td align="right">9</td>
<td align="right">262</td>
</tr>
<tr class="even">
<td align="right">2023</td>
<td align="right">10</td>
<td align="right">35</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">6</td>
<td align="right">36</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">7</td>
<td align="right">349</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">8</td>
<td align="right">279</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">9</td>
<td align="right">27</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">10</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
<p>To determine whether year is a significant additional predictor to a
model that already has linear and second order terms for month, we
created a Poisson model with just the two month terms and one with both
month terms and year as a predictor.</p>
<pre class="r"><code>fit3.5 &lt;- glm(count ~ month + I(month^2), mosq_month_year, family = &quot;poisson&quot;)
fit4 &lt;- glm(count ~ month + I(month^2) + year, mosq_month_year, family = &quot;poisson&quot;)

fit3.5 |&gt; 
  tidy() |&gt; 
  knitr::kable(
    digits = 4,
    col.names = c(&quot;Term&quot;, &quot;Estimate&quot;, &quot;Standard error&quot;, &quot;Test statistic&quot;, &quot;p value&quot;)
  )</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Term</th>
<th align="right">Estimate</th>
<th align="right">Standard error</th>
<th align="right">Test statistic</th>
<th align="right">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-36.0546</td>
<td align="right">1.2560</td>
<td align="right">-28.7065</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">month</td>
<td align="right">10.3797</td>
<td align="right">0.3115</td>
<td align="right">33.3251</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">I(month^2)</td>
<td align="right">-0.6434</td>
<td align="right">0.0192</td>
<td align="right">-33.5201</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<pre class="r"><code>fit3.5 |&gt; 
  glance() |&gt; 
  knitr::kable(
    digits = 4,
    col.names = c(&quot;Null deviance&quot;, &quot;Null df&quot;, &quot;Log likelihood&quot;, &quot;AIC&quot;, &quot;BIC&quot;, &quot;Deviance&quot;, &quot;Residual df&quot;, &quot;Number of observations&quot;)
  )</code></pre>
<table>
<colgroup>
<col width="14%" />
<col width="8%" />
<col width="15%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="12%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Null deviance</th>
<th align="right">Null df</th>
<th align="right">Log likelihood</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">Deviance</th>
<th align="right">Residual df</th>
<th align="right">Number of observations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2472.735</td>
<td align="right">18</td>
<td align="right">-395.8216</td>
<td align="right">797.6431</td>
<td align="right">800.4764</td>
<td align="right">675.8574</td>
<td align="right">16</td>
<td align="right">19</td>
</tr>
</tbody>
</table>
<pre class="r"><code>fit4 |&gt; 
  tidy() |&gt; 
  knitr::kable(
    digits = 4,
    col.names = c(&quot;Term&quot;, &quot;Estimate&quot;, &quot;Standard error&quot;, &quot;Test statistic&quot;, &quot;p value&quot;)
  )</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Term</th>
<th align="right">Estimate</th>
<th align="right">Standard error</th>
<th align="right">Test statistic</th>
<th align="right">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">12.5237</td>
<td align="right">33.3785</td>
<td align="right">0.3752</td>
<td align="right">0.7075</td>
</tr>
<tr class="even">
<td align="left">month</td>
<td align="right">10.3857</td>
<td align="right">0.3114</td>
<td align="right">33.3503</td>
<td align="right">0.0000</td>
</tr>
<tr class="odd">
<td align="left">I(month^2)</td>
<td align="right">-0.6437</td>
<td align="right">0.0192</td>
<td align="right">-33.5435</td>
<td align="right">0.0000</td>
</tr>
<tr class="even">
<td align="left">year</td>
<td align="right">-0.0240</td>
<td align="right">0.0165</td>
<td align="right">-1.4564</td>
<td align="right">0.1453</td>
</tr>
</tbody>
</table>
<pre class="r"><code>fit4 |&gt; 
  glance() |&gt; 
  knitr::kable(
    digits = 4,
    col.names = c(&quot;Null deviance&quot;, &quot;Null df&quot;, &quot;Log likelihood&quot;, &quot;AIC&quot;, &quot;BIC&quot;, &quot;Deviance&quot;, &quot;Residual df&quot;, &quot;Number of observations&quot;)
  )</code></pre>
<table>
<colgroup>
<col width="14%" />
<col width="8%" />
<col width="15%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="12%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Null deviance</th>
<th align="right">Null df</th>
<th align="right">Log likelihood</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">Deviance</th>
<th align="right">Residual df</th>
<th align="right">Number of observations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2472.735</td>
<td align="right">18</td>
<td align="right">-394.7607</td>
<td align="right">797.5213</td>
<td align="right">801.2991</td>
<td align="right">673.7356</td>
<td align="right">15</td>
<td align="right">19</td>
</tr>
</tbody>
</table>
<pre class="r"><code>anova(fit3.5, fit4) |&gt; 
  tidy()</code></pre>
<pre><code>## # A tibble: 2 × 6
##   term                      df.residual residual.deviance    df deviance p.value
##   &lt;chr&gt;                           &lt;dbl&gt;             &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 count ~ month + I(month^…          16              676.    NA    NA     NA    
## 2 count ~ month + I(month^…          15              674.     1     2.12   0.145</code></pre>
<p>In the model with year as a predictor, year is not significantly
predicting mosquito counts, with a p value of 0.1453. When conducting a
chi-squared test to determine whether the addition of year is
significant, the associated p value is 0.1452. Adding year to a model
that already has month as linear and second order terms does not
significantly improve model prediction.</p>
</div>
<div id="model-with-week-and-temperature" class="section level1">
<h1>Model with week and temperature</h1>
<p>To create a model that includes week as a parameter, we need
aggregated mosquito counts by year and week. This is done again by
<code>mutate</code> to make year and week variables, creating a variable
<code>weekyear</code> that calculates the number of weeks from 2021 (the
first year of available mosquito data), and grouping counts by
combinations of year and week.</p>
<pre class="r"><code>mosq_cases &lt;-
  wnv_mosquitoes |&gt;
  mutate(
    year = lubridate::year(date),
    week = lubridate::week(date)) |&gt;
  group_by(year, week) |&gt;
  summarise(count = n()) |&gt;
  mutate(weekyear = (year - 2021)*52 + week) |&gt;
  filter(year &lt; 3000)</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;year&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre class="r"><code>wnv_mosquitoes |&gt;
  mutate(
    year = lubridate::year(date),
    week = lubridate::week(date)) |&gt;
  group_by(year, week) |&gt;
  summarise(count = n()) |&gt;
  mutate(weekyear = (year - 2021)*52 + week) </code></pre>
<pre><code>## `summarise()` has grouped output by &#39;year&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre><code>## # A tibble: 64 × 4
## # Groups:   year [4]
##     year  week count weekyear
##    &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;
##  1  2021    25     4       25
##  2  2021    27    24       27
##  3  2021    28    31       28
##  4  2021    30    47       30
##  5  2021    31    60       31
##  6  2021    32   152       32
##  7  2021    33    77       33
##  8  2021    35   144       35
##  9  2021    37    95       37
## 10  2021    38    35       38
## # ℹ 54 more rows</code></pre>
<pre class="r"><code>mosq_cases |&gt; 
  mutate(
    year_2021 = year - 2021,
    year_2021x52 = (year - 2021) * 52
  ) |&gt; 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">year</th>
<th align="right">week</th>
<th align="right">count</th>
<th align="right">weekyear</th>
<th align="right">year_2021</th>
<th align="right">year_2021x52</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2021</td>
<td align="right">25</td>
<td align="right">4</td>
<td align="right">25</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2021</td>
<td align="right">27</td>
<td align="right">24</td>
<td align="right">27</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">2021</td>
<td align="right">28</td>
<td align="right">31</td>
<td align="right">28</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2021</td>
<td align="right">30</td>
<td align="right">47</td>
<td align="right">30</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">2021</td>
<td align="right">31</td>
<td align="right">60</td>
<td align="right">31</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2021</td>
<td align="right">32</td>
<td align="right">152</td>
<td align="right">32</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">2021</td>
<td align="right">33</td>
<td align="right">77</td>
<td align="right">33</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2021</td>
<td align="right">35</td>
<td align="right">144</td>
<td align="right">35</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">2021</td>
<td align="right">37</td>
<td align="right">95</td>
<td align="right">37</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2021</td>
<td align="right">38</td>
<td align="right">35</td>
<td align="right">38</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">2021</td>
<td align="right">40</td>
<td align="right">47</td>
<td align="right">40</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2021</td>
<td align="right">41</td>
<td align="right">13</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">2021</td>
<td align="right">42</td>
<td align="right">3</td>
<td align="right">42</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">26</td>
<td align="right">8</td>
<td align="right">78</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="odd">
<td align="right">2022</td>
<td align="right">27</td>
<td align="right">11</td>
<td align="right">79</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">28</td>
<td align="right">17</td>
<td align="right">80</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="odd">
<td align="right">2022</td>
<td align="right">29</td>
<td align="right">28</td>
<td align="right">81</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">30</td>
<td align="right">53</td>
<td align="right">82</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="odd">
<td align="right">2022</td>
<td align="right">31</td>
<td align="right">79</td>
<td align="right">83</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">32</td>
<td align="right">92</td>
<td align="right">84</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="odd">
<td align="right">2022</td>
<td align="right">33</td>
<td align="right">95</td>
<td align="right">85</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">34</td>
<td align="right">92</td>
<td align="right">86</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="odd">
<td align="right">2022</td>
<td align="right">35</td>
<td align="right">82</td>
<td align="right">87</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">36</td>
<td align="right">70</td>
<td align="right">88</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="odd">
<td align="right">2022</td>
<td align="right">37</td>
<td align="right">61</td>
<td align="right">89</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">38</td>
<td align="right">50</td>
<td align="right">90</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="odd">
<td align="right">2022</td>
<td align="right">39</td>
<td align="right">30</td>
<td align="right">91</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="right">2022</td>
<td align="right">40</td>
<td align="right">14</td>
<td align="right">92</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="odd">
<td align="right">2022</td>
<td align="right">41</td>
<td align="right">7</td>
<td align="right">93</td>
<td align="right">1</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="right">2023</td>
<td align="right">27</td>
<td align="right">5</td>
<td align="right">131</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="odd">
<td align="right">2023</td>
<td align="right">28</td>
<td align="right">11</td>
<td align="right">132</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="even">
<td align="right">2023</td>
<td align="right">29</td>
<td align="right">23</td>
<td align="right">133</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="odd">
<td align="right">2023</td>
<td align="right">30</td>
<td align="right">33</td>
<td align="right">134</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="even">
<td align="right">2023</td>
<td align="right">31</td>
<td align="right">41</td>
<td align="right">135</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="odd">
<td align="right">2023</td>
<td align="right">32</td>
<td align="right">57</td>
<td align="right">136</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="even">
<td align="right">2023</td>
<td align="right">33</td>
<td align="right">73</td>
<td align="right">137</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="odd">
<td align="right">2023</td>
<td align="right">34</td>
<td align="right">86</td>
<td align="right">138</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="even">
<td align="right">2023</td>
<td align="right">35</td>
<td align="right">85</td>
<td align="right">139</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="odd">
<td align="right">2023</td>
<td align="right">36</td>
<td align="right">79</td>
<td align="right">140</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="even">
<td align="right">2023</td>
<td align="right">37</td>
<td align="right">72</td>
<td align="right">141</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="odd">
<td align="right">2023</td>
<td align="right">38</td>
<td align="right">68</td>
<td align="right">142</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="even">
<td align="right">2023</td>
<td align="right">39</td>
<td align="right">43</td>
<td align="right">143</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="odd">
<td align="right">2023</td>
<td align="right">40</td>
<td align="right">17</td>
<td align="right">144</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="even">
<td align="right">2023</td>
<td align="right">41</td>
<td align="right">11</td>
<td align="right">145</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="odd">
<td align="right">2023</td>
<td align="right">42</td>
<td align="right">5</td>
<td align="right">146</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="even">
<td align="right">2023</td>
<td align="right">43</td>
<td align="right">2</td>
<td align="right">147</td>
<td align="right">2</td>
<td align="right">104</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">23</td>
<td align="right">2</td>
<td align="right">179</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">24</td>
<td align="right">3</td>
<td align="right">180</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">25</td>
<td align="right">9</td>
<td align="right">181</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">26</td>
<td align="right">22</td>
<td align="right">182</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">27</td>
<td align="right">50</td>
<td align="right">183</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">28</td>
<td align="right">64</td>
<td align="right">184</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">29</td>
<td align="right">100</td>
<td align="right">185</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">30</td>
<td align="right">101</td>
<td align="right">186</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">31</td>
<td align="right">88</td>
<td align="right">187</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">32</td>
<td align="right">74</td>
<td align="right">188</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">33</td>
<td align="right">66</td>
<td align="right">189</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">34</td>
<td align="right">49</td>
<td align="right">190</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">35</td>
<td align="right">36</td>
<td align="right">191</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">36</td>
<td align="right">17</td>
<td align="right">192</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">37</td>
<td align="right">4</td>
<td align="right">193</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">38</td>
<td align="right">5</td>
<td align="right">194</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="odd">
<td align="right">2024</td>
<td align="right">39</td>
<td align="right">1</td>
<td align="right">195</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
<tr class="even">
<td align="right">2024</td>
<td align="right">40</td>
<td align="right">1</td>
<td align="right">196</td>
<td align="right">3</td>
<td align="right">156</td>
</tr>
</tbody>
</table>
<pre class="r"><code>weekly_weather &lt;- 
  day_weather |&gt;
  mutate(
    year = lubridate::year(date),
    week = lubridate::week(date)) |&gt;
  group_by(year, week) |&gt;
  summarise(avg_temp = mean(avg_temp),
            avg_prcp = mean(avg_prcp),
            avg_dewp = mean(avg_dewp),
            avg_max = mean(avg_max),
            avg_min = mean(avg_min)) |&gt;
  arrange(year, week) |&gt;
  mutate(lag_temp = lag(avg_temp),
         lag_prcp = lag(avg_prcp),
         lag_dewp = lag(avg_dewp),
         lag_max =  lag(avg_max),
         lag_min =  lag(avg_min)) |&gt;
  mutate(weekyear = (year - 2021)*52 + week) #week since start of 2021</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;year&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre class="r"><code>mosq_cases_temp &lt;- mosq_cases |&gt;
  left_join(y = weekly_weather, by = join_by(weekyear)) |&gt;
  select(-ends_with(&quot;.y&quot;)) |&gt;
  rename(year = year.x, week = week.x) |&gt;
  mutate(
    lag_count = lag(count),
    lag_count = case_when(
      is.na(lag_count) ~ 0,
      .default = lag_count
    )
  ) |&gt;
  na.omit()</code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
