---
title: "shiny_dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(rvest)
library(httr)
library(GSODR)
library(sf)
library(plotly)

```

```{r, include = FALSE}

# ZIP code to neighborhood 
zip_nbhd <- read_html("https://p8105.com/data/zip_codes.html") |>
  html_table() |>
  first() |>
  janitor::clean_names() |>
  filter(!(county == "New York" & zip_code %in% c(10463, 11201))) |>#duplicated zip codes, both are *not* in New York County
  mutate(borough = str_replace_all(county, c(
    "Kings" = "Brooklyn",
    "New York" = "Manhattan",
    "Richmond" = "Staten Island"
  ))) |>
  select(zip_code, borough, neighborhood)


# NYC WNV+ mosquito data import

## 2021 - 2023 are simple HTML tables
mosquitoes_2024_url <- "https://www.nyc.gov/site/doh/health/health-topics/west-nile-virus-activity-2024.page"
mosquitoes_2023_url <- "https://www.nyc.gov/site/doh/health/health-topics/west-nile-virus-activity-2023.page"
mosquitoes_2022_url <- "https://www.nyc.gov/site/doh/health/health-topics/west-nile-virus-activity-2022.page"
mosquitoes_2021_url <- "https://www.nyc.gov/site/doh/health/health-topics/west-nile-virus-activity-2021.page"

### 2024
mosquitoes_2024_table <- read_csv("data/mosquitoes_2024.csv") |>
  pivot_longer(cols = starts_with("date"), values_to = "date") |>
  select(-name, -detection_type) |> 
  mutate(
    date = case_when(
      date == "8/5/5024" ~ "8/5/2024",
      .default = date # one observation, 11426, with year miswritten as 5024-08-05 instead of 2024-08-05
    ),
    date = lubridate::mdy(date)
  ) |> 
  na.omit() 
   
### 2023
mosquitoes_2023_table <- mosquitoes_2023_url |>
  read_html() |> html_table() |> first() |>
  janitor::clean_names() |>
  separate_longer_delim(zip_code, delim = ", ") |>
  separate_longer_delim(zip_code, delim = ",\n") |>
  separate_longer_delim(zip_code, delim = ",") |> #this data is disgusting
  select(-neighborhood, -download) |>
  mutate(
    zip_code = as.integer(zip_code),
    date = str_c(date, ", ", 2023),
    date = lubridate::mdy(date)
  )

### 2022
mosquitoes_2022_table <- mosquitoes_2022_url |>
  read_html() |> html_table() |> first() |>
  janitor::clean_names() |>
  separate_longer_delim(zip_code, delim = ", ") |>
  separate_longer_delim(zip_code, delim = ",\n") |>
  separate_longer_delim(zip_code, delim = ",") |> #this data is disgusting
  select(-download) |>
  mutate(
    zip_code = as.integer(zip_code),
    date = str_c(date, ", ", 2022),
    date = lubridate::mdy(date)
  )

### 2021
mosquitoes_2021_table <- mosquitoes_2021_url |>
  read_html() |> html_table() |> first() |>
  janitor::clean_names() |>
  separate_longer_delim(zip_code, delim = ", ") |>
  separate_longer_delim(zip_code, delim = ",\n") |>
  separate_longer_delim(zip_code, delim = ",") |> #this data is disgusting
  select(-download) |>
  mutate(
    zip_code = as.integer(zip_code),
    date = str_c(date, ", ", 2021),
    date = lubridate::mdy(date)
  ) |> 
  mutate(
    zip_code = case_when(
      zip_code == 1123 ~ 11236, # data entry error on the website, where 1123 is missing the last digit - per https://www.nyc.gov/assets/doh/downloads/pdf/wnv/2021/wnv-activity-bk-08192021.pdf it should be 11236
    .default = zip_code
    )
  )

wnv_mosquito_detection <- bind_rows(
  mosquitoes_2024_table,
  mosquitoes_2023_table,
  mosquitoes_2022_table,
  mosquitoes_2021_table,
) |> 
  left_join(y = zip_nbhd, by = join_by(zip_code)) |>
  select(zip_code, borough.x, date, neighborhood) |> 
  rename(borough = borough.x) |> # one ZIP code, 10000 has NA for borough as it is not in ZIP list - Central Park based on a Google search
  mutate(
    borough = case_when(
      zip_code == 10000 ~ "Manhattan",
      .default = borough
    ),
    neighborhood = case_when(
      zip_code == 10000 ~ "Central Park",
      .default = neighborhood
    )
  )

######### West Nile Virus Cases by Year and Borough
wnv_cases <- read_csv("data/wnv_cases.csv") |>
  janitor::clean_names() |>
  pivot_longer(cols = c(
    bronx,
    brooklyn,
    manhattan,
    queens,
    staten_island
  ),
  names_to = "borough",
  values_to = "wnv_cases") |> 
  mutate(
    borough = case_match(
      borough, 
      "manhattan" ~ "Manhattan",
      "brooklyn" ~ "Brooklyn",
      "queens" ~ "Queens",
      "bronx" ~ "Bronx",
      "staten_island" ~ "Staten Island"
    )
  )

# Weather data from GSOD

day_weather <- 
  read_csv("cleaned_data/day_weather.csv") |> 
  mutate(
    year = year(date)
  )

yearly_weather <-
  read_csv("cleaned_data/yearly_weather.csv")


hvi_zcta <- read_csv("https://data.cityofnewyork.us/resource/4mhf-duep.csv")  |> 
  rename(zip_code = zcta20)

# Get MODZCTA shapefile data for mapping detected WNV+ mosquitos

path <- "data/shapefiles/MODZCTA_2010.shp"

zip_shp <-
  path |>
  st_read() |> 
  drop_na(label) |> # gets rid of MODZCTA 99999 which is not a real MODZCTA 
  separate_longer_delim(label, delim = ", ") |> 
  janitor::clean_names() |> 
  mutate(
    modzcta = as.double(modzcta),
    zip_code = as.double(label)
  ) |> 
  separate_longer_delim(label, delim = ", ")

# Add 0s for MODZCTAs without detected WNV+ mosquitoes

all_zctas <-
  zip_nbhd |> 
  pull(zip_code) |> 
  c(10000) |> 
  expand_grid(
    zip_code = _,
    year = c(2021, 2022, 2023, 2024),
    count = 0
  )

fill_neg_zctas <- function(yr) {
  
  pos = 
    wnv_mosquito_detection |> 
    mutate(
      year = year(date)
    ) |> 
    filter(year == yr) |> 
    group_by(zip_code, neighborhood, year) |> 
    summarize(
      count = n()
    ) |>
    arrange(count)
  
  neg = 
    all_zctas |> 
    filter(year == yr) |> 
    anti_join(pos, by = join_by(zip_code))
  
  rbind(pos, neg)
    
}

wnv_mosquito_data <-
  tibble(
    years = c(2021, 2022, 2023, 2024),
    mosquito_data = map(years, fill_neg_zctas)
  ) |> 
  unnest(mosquito_data) |> 
  select(-years) |> 
  left_join(zip_nbhd, by = join_by(zip_code, neighborhood)) |> # rejoin borough variable from original ZIP code list 
  mutate(
    borough = case_when(
      zip_code == 10000 ~ "Manhattan",
      .default = borough
    ),
    neighborhood = case_when(
      zip_code == 10000 ~ "Central Park",
      .default = neighborhood
    ),
    
  )


# Merge mosquito data with shapefiles by MODZCTA

mos_by_modzcta <- 
  left_join(wnv_mosquito_data, zip_shp, by = join_by("zip_code")) |> 
  mutate(
    neighborhood = case_when(
      is.na(neighborhood) ~ "Non-residential",
      .default = neighborhood
    )
  )


# Combine WNV human case, WNV mosquitoes, HVI, and temperature data

avg_hvi_borough <-
  left_join(hvi_zcta, zip_nbhd, by = join_by(zip_code)) |> 
    group_by(borough) |> 
    summarize(
      avg_hvi = mean(hvi)
    )

wnv_case_temp_hvi_df <- 
  wnv_mosquito_data |> 
  filter(!is.na(borough)) |>  # there are (likely nonresidential) ZIP codes with no boroughs and no detected WNV in mosquitoes and humans
  group_by(year, borough) |> 
  summarize(
    wnv_mosquitoes = sum(count) 
  ) |> 
  right_join(wnv_cases, by = join_by(year, borough)) |> 
  left_join(yearly_weather, by = join_by(year)) |> 
  left_join(avg_hvi_borough, by = join_by(borough)) |>  
  select(year, borough, starts_with("wnv_"), everything()) |> 
  arrange(year, borough)

```

Sidebar {.sidebar}
-----------------------------------------------------------------------

```{r, echo=FALSE}
years <- 
  mos_by_modzcta |> 
  pull(year) |> 
  unique() 

selectInput(
  inputId = "year_choice",
  label = h3("Select year"),
  choices = years, selected = 2024
)

boroughs <-
  mos_by_modzcta |>
  drop_na(borough) |> 
  pull(borough) |> 
  unique() 

radioButtons(
  inputId = "borough_choice",
  label = h3("Select borough(s)"),
  choices = boroughs, selected = "Manhattan"
)

max_mosquitoes <- 25 
min_mosquitoes <- 
  mos_by_modzcta |> 
  distinct(count) |> 
  min()

sliderInput(
  inputId = "mosquito_range",
  label = h3("Choose range of WNV+ mosquitoes"),
  min = min_mosquitoes, max = max_mosquitoes, value = c(0,25)
)
```


Column
-----------------------------------------------------------------------

### Citywide WNV+ mosquitoes by ZIP code per year

```{r, echo=FALSE}
renderPlotly({
  plot <-
    mos_by_modzcta |>
    filter(!st_is_empty(geometry) & year == input$year_choice) |>
    ggplot(aes(fill = count, geometry = geometry, text = paste(zip_code, " - ", neighborhood))) +
    geom_sf() +
    labs(
      fill = "WNV+ mosquitoes"
    ) +
    theme(
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      axis.text.y = element_blank(),
      axis.title.y = element_blank()
    ) +
    viridis::scale_fill_viridis(limits = c(0, 25))
  
  ggplotly(plot)
})
```

### Most WNV+ detected ZIP codes by borough

```{r, echo=FALSE}
renderPlotly({
  mos_by_modzcta |> 
  filter(
    !st_is_empty(geometry),
    year == input$year_choice,
    count %in% input$mosquito_range[1]:input$mosquito_range[2],
    borough == input$borough_choice
  ) |>
  mutate(
    zip_code = as.factor(zip_code),
    zip_code = fct_reorder(zip_code, count),
    text_label = str_c(zip_code, " - ", neighborhood, ", ", borough)
  ) |> 
  plot_ly(x = ~zip_code, y = ~count, color = ~zip_code, text = ~text_label, type = "bar", colors = "viridis")
})
```


